#!/usr/bin/env node
// CLI: imagegen --prompt "..." --number 2 --aspect_ratio 16:9 --reference_file cat.png
import path from 'node:path';

import { resolveConfig, resolveAspectRatio } from './config.js';
import { checkAuth } from './auth.js';
import { normalizeNumber } from './options.js';
import { createProvider } from './providers/createProvider.js';
import { SUPPORTED_PROVIDERS, type ProviderId } from './providers/types.js';

interface ParsedArgs {
  prompt: string | null;
  number: number | string;
  aspect_ratio: string;
  reference_file: string[];
  outputDir: string | null;
  model: string | null;
  provider: string | null;
  dryRun: boolean;
  auth: boolean;
  help: boolean;
}

function parseArgs(argv: string[]): ParsedArgs {
  const args: ParsedArgs = {
    prompt: null,
    number: 1,
    aspect_ratio: '1:1',
    reference_file: [],
    outputDir: null,
    model: null,
    provider: null,
    dryRun: false,
    auth: false,
    help: false
  };

  function readValue(flag: string, next: string | undefined): string {
    if (!next || next.startsWith('-')) {
      throw new Error(`${flag} requires a value.`);
    }
    return next;
  }

  for (let i = 0; i < argv.length; i++) {
    const t = argv[i];
    if (!t) continue;
    const next = argv[i + 1];
    switch (t) {
      case '--prompt': case '-p': args.prompt = readValue(t, next); i++; break;
      // Store the raw value; validation is centralized via normalizeNumber so
      // every surface rejects (rather than floors/clamps/defaults) bad input.
      case '--number': case '-n': args.number = readValue(t, next); i++; break;
      case '--aspect_ratio': case '-a': args.aspect_ratio = readValue(t, next); i++; break;
      case '--reference_file': case '-r': args.reference_file.push(readValue(t, next)); i++; break;
      case '--output-dir': case '-o': args.outputDir = readValue(t, next); i++; break;
      case '--output-prefix': throw new Error('--output-prefix is not supported; filenames are generated by the API.');
      case '--model': case '-m': args.model = readValue(t, next); i++; break;
      case '--provider': args.provider = readValue(t, next); i++; break;
      case '--dry-run': args.dryRun = true; break;
      case '--auth': args.auth = true; break;
      case '--help': case '-h': args.help = true; break;
      default:
        if (!t.startsWith('-') && !args.prompt) { args.prompt = t; }
        else throw new Error(`Unknown argument: ${t}`);
    }
  }
  return args;
}

function printHelp(): void {
  console.log(`
imagegen - Fast image generation via Codex private backend

Usage:
  imagegen --prompt "a sunset over mountains" [options]

Options:
  -p, --prompt <text>          Required: image generation prompt
  -n, --number <int>           Number of images to generate (1-4, default: 1)
                              (codex only; codex-cli fails fast when >1)
  -a, --aspect_ratio <ratio>   Aspect ratio: 1:1, 3:2, 2:3, 16:9, 9:16, 4:3, 3:4, auto
                              Or raw size: 1024x1024, 1536x1024, 2048x1152, etc. (default: 1:1)
                              (codex only; codex-cli cannot honor size)
  -r, --reference_file <path>  Reference image path (repeatable for multiple)
                              (codex only; codex-cli cannot accept images)
  -o, --output-dir <dir>       Output root (default: ./outputs)
  -m, --model <name>           Model name (default: gpt-5.4)
  --provider <name>            Provider: codex | codex-cli | auto (default: codex)
                              auto = try codex, fall back to codex-cli on failure
                              (fallback refused when --number >1, --aspect_ratio/--size, or -r are set)
  --dry-run                    Validate auth and print request without calling backend
  --auth                       Check authentication status
  -h, --help                   Show this help

Prerequisites:
  1. Install Codex CLI: npm install -g @openai/codex
  2. Login with ChatGPT: codex login
  3. Verify: imagegen --auth

Examples:
  imagegen --prompt "a flat blue square icon" -o ./outputs/generate
  imagegen -p "sunset over mountains" -n 2 -a 16:9 -o ./outputs/generate
  imagegen -p "make this cat wear a hat" -r ./cat.png -o ./outputs/generate
  imagegen --provider codex-cli -p "a red square" -o ./outputs/generate
  imagegen --auth
`);
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) { printHelp(); return; }

  if (args.provider && !SUPPORTED_PROVIDERS.includes(args.provider as ProviderId)) {
    throw new Error(`Unsupported --provider: ${args.provider}. Supported: ${SUPPORTED_PROVIDERS.join(', ')}.`);
  }

  const config = resolveConfig({
    model: args.model ?? undefined,
    defaultOutputDir: args.outputDir ?? undefined,
    provider: args.provider ?? undefined
  });

  if (args.auth) {
    const status = await checkAuth(config);
    if (status.ok) {
      console.log('Authentication: OK');
      console.log(`  auth_mode: ${status.authMode}`);
      console.log(`  access_token: present`);
      console.log(`  account_id: present`);
      console.log(`  installation_id: ${status.hasInstallationId ? 'present' : 'missing'}`);
      if (status.warnings.length) {
        for (const w of status.warnings) console.warn(`  warning: ${w}`);
      }
    } else {
      console.error('Authentication: FAILED');
      console.error(`  ${status.error}`);
      console.error('\nTo fix:');
      console.error('  1. npm install -g @openai/codex');
      console.error('  2. codex login');
      console.error('  3. imagegen --auth');
      process.exitCode = 1;
    }
    return;
  }

  if (!args.prompt) {
    printHelp();
    process.exitCode = 1;
    return;
  }

  // Centralized number validation: rejects non-integers and values outside
  // 1..4 consistently for every provider path instead of flooring/clamping.
  args.number = normalizeNumber(args.number);

  // Single code path: all providers go through the provider factory.
  // codex returns images[] with multi-image support; codex-cli returns
  // a single savedPath; auto falls back and fails fast when codex-cli can't
  // honor the requested options.
  const provider = createProvider(config);
  const outputDir = path.resolve(args.outputDir || config.defaultOutputDir);
  const size = args.aspect_ratio && args.aspect_ratio !== '1:1' ? resolveAspectRatio(args.aspect_ratio) : undefined;

  const result = await provider.generateImage({
    prompt: args.prompt,
    number: args.number,
    model: args.model || config.model,
    outputDir,
    dryRun: args.dryRun,
    ...(args.reference_file.length > 0 ? { images: args.reference_file } : {}),
    ...(size ? { size } : {})
  });

  if (result.mode === 'dry-run') {
    console.log(JSON.stringify(result, null, 2));
    return;
  }

  for (const w of result.warnings) console.warn(`warning: ${w}`);

  // Both provider variants populate `images[]` — use it uniformly.
  // codex-cli returns a single-element array; codex returns N elements.
  const images = result.images ?? [];
  console.log(JSON.stringify({
    provider: result.provider,
    count: images.length,
    images: images.map((img) => ({
      savedPath: img.savedPath,
      relativePath: img.relativePath,
      revisedPrompt: img.revisedPrompt,
      responseId: img.responseId,
      sessionId: img.sessionId
    })),
    outputRoot: result.outputRoot,
    outputDir: result.outputDir,
    relativeOutputDir: result.relativeOutputDir,
    slug: result.slug
  }, null, 2));
}

main().catch((e: unknown) => {
  console.error((e as Error)?.message || String(e));
  process.exitCode = 1;
});
