import { resolveAspectRatio } from './config.js';

export function normalizeReferenceFile(value: string | string[] | undefined | null): string[] {
  if (!value) return [];
  if (Array.isArray(value)) {
    return value.map((v) => {
      if (typeof v !== 'string' || !v.trim()) {
        throw new TypeError('reference_file entries must be non-empty strings.');
      }
      return v;
    });
  }
  if (typeof value === 'string' && value.trim()) return [value];
  throw new TypeError('reference_file must be a string or an array of strings.');
}

export function normalizeNumber(value: number | string = 1): number {
  const number = Number(value);
  if (!Number.isFinite(number) || number < 1) {
    throw new Error(`number must be a positive integer, got: ${value ?? '(missing)'}`);
  }
  if (!Number.isInteger(number)) {
    throw new Error(`number must be an integer, got: ${value}`);
  }
  if (number > 4) {
    throw new Error(`number must be between 1 and 4, got: ${value}`);
  }
  return number;
}

export interface GenerationOptionsInput {
  prompt?: string;
  number?: number | string;
  aspect_ratio?: string;
  reference_file?: string | string[];
  outputDir?: string;
  outputPrefix?: string;
}

export interface NormalizedGenerationOptions {
  prompt: string;
  number: number;
  aspectRatio: string;
  size: string;
  referenceFiles: string[];
  outputDir: string | undefined;
}

export interface GenerationDefaults {
  aspect_ratio?: string;
  number?: number | string;
  outputDir?: string;
  outputPrefix?: string;
}

export function normalizeGenerationOptions(
  opts: GenerationOptionsInput,
  defaults: GenerationDefaults = {}
): NormalizedGenerationOptions {
  if (!opts?.prompt?.trim()) throw new Error('prompt is required.');
  if (opts.outputPrefix || defaults.outputPrefix) {
    throw new Error('outputPrefix is not supported; filenames are generated by the API.');
  }

  const aspectRatio = opts.aspect_ratio || defaults.aspect_ratio || '1:1';
  return {
    prompt: opts.prompt,
    number: normalizeNumber(opts.number ?? defaults.number ?? 1),
    aspectRatio,
    size: resolveAspectRatio(aspectRatio),
    referenceFiles: normalizeReferenceFile(opts.reference_file),
    outputDir: opts.outputDir || defaults.outputDir
  };
}
