// codex provider: thin adapter over generateImage so the provider
// interface matches the codex-cli provider (single image per call, returns
// { mode, provider, warnings, responseId, sessionId, savedPath, revisedPrompt }).
import path from 'node:path';

import { generateImage as generateImageCore } from '../generate.js';
import { resolveAspectRatio } from '../config.js';
import type { Config } from '../config.js';
import type { Provider, ProviderGenerateArgs, CodexResult } from './provider.js';
import { CODEX_PROVIDER } from './types.js';

export function createCodexProvider(config: Config): Provider {
  return {
    async generateImage({
      prompt,
      model,
      outputDir,
      outputPath,
      dryRun = false,
      images,
      size,
      outputPrefix,
      number = 1
    }: ProviderGenerateArgs): Promise<CodexResult> {
      if (!prompt || !prompt.trim()) throw new Error('prompt is required.');
      const aspectRatio = size && size !== 'auto' ? size : 'auto';
      // Validate size early via resolveAspectRatio when not auto.
      if (size && size !== 'auto') resolveAspectRatio(size);
      if (outputPrefix) {
        throw new Error('outputPrefix is not supported; filenames are generated by the API.');
      }

      const outputRoot = outputDir || (outputPath ? path.dirname(outputPath) : config.defaultOutputDir);

      const result = await generateImageCore({
        prompt,
        number,
        aspect_ratio: aspectRatio,
        reference_file: images,
        outputDir: outputRoot,
        config: model ? { ...config, model } : config,
        dryRun
      });

      if (dryRun) {
        return {
          mode: 'dry-run',
          provider: CODEX_PROVIDER,
          warnings: result.warnings,
          images: result.images,
          outputRoot: result.outputRoot,
          outputDir: result.outputDir,
          relativeOutputDir: result.relativeOutputDir,
          slug: result.slug
        };
      }

      const img = result.images[0];
      return {
        mode: 'live',
        provider: CODEX_PROVIDER,
        warnings: result.warnings,
        responseId: img?.responseId,
        sessionId: img?.sessionId,
        images: result.images,
        outputRoot: result.outputRoot,
        outputDir: result.outputDir,
        relativeOutputDir: result.relativeOutputDir,
        slug: result.slug
      };
    }
  };
}
