// Provider factory: selects codex, codex-cli, or auto (fallback).
import { CodedError } from '../errors.js';
import { createCodexCliProvider } from './codexCli.js';
import { createCodexProvider } from './codex.js';
import { AUTO_PROVIDER, CODEX_CLI_PROVIDER, CODEX_PROVIDER } from './types.js';
import type { Config } from '../config.js';
import type { Provider, ProviderGenerateArgs, ProviderResult } from './provider.js';

export function createProvider(config: Config): Provider {
  const codexProvider = createCodexProvider(config);
  const cliProvider = createCodexCliProvider(config);

  switch (config.provider) {
    case CODEX_PROVIDER:
      return codexProvider;
    case CODEX_CLI_PROVIDER:
      return cliProvider;
    case AUTO_PROVIDER:
      return {
        async generateImage(args: ProviderGenerateArgs): Promise<ProviderResult> {
          if (args.outputPrefix) {
            throw new Error('outputPrefix is not supported; filenames are generated by the API.');
          }
          try {
            return await codexProvider.generateImage(args);
          } catch (codexError) {
            // The codex-cli provider does not wire --image or size through to
            // codex exec, so refuse to fall back when those were requested
            // rather than silently dropping the user's intent.
            if (args?.size && args.size !== 'auto') {
              throw new CodedError(
                'The auto provider cannot fall back to codex-cli when --size is set because the codex-cli provider does not wire output dimensions through to codex exec.',
                'SIZE_UNSUPPORTED_BY_FALLBACK',
                { cause: codexError }
              );
            }
            if (args?.images && args.images.length > 0) {
              throw new CodedError(
                'The auto provider cannot fall back to codex-cli when reference images are provided because the codex-cli provider does not wire --image through to codex exec.',
                'IMAGES_UNSUPPORTED_BY_FALLBACK',
                { cause: codexError }
              );
            }
            if (args?.number && Number(args.number) > 1) {
              throw new CodedError(
                'The auto provider cannot fall back to codex-cli when multiple images are requested because codex-cli cannot generate multiple images.',
                'NUMBER_UNSUPPORTED_BY_FALLBACK',
                { cause: codexError }
              );
            }
            const cliResult = await cliProvider.generateImage(args);
            const codexCode = codexError instanceof CodedError ? codexError.code : (codexError as Error).message;
            if (cliResult.provider === CODEX_CLI_PROVIDER) {
              return {
                ...cliResult,
                warnings: [
                  ...cliResult.warnings,
                  `Primary provider failed and auto fallback switched to codex-cli: ${codexCode}`
                ]
              };
            }
            return cliResult;
          }
        }
      };
    default:
      throw new Error(`Unsupported provider: ${config.provider}`);
  }
}
